### ISSUE TITLE
Build system fixes

### ISSUE THREAD

**Issue by PyroAVR** [FleventyFive/TinyRogue#1]
- Fixed `make` crash when `$(OBJ)`, `$(TARGET)` dirs not present
 - Added 'clean' target to Makefile.

[fix_patch.txt](https://github.com/FleventyFive/TinyRogue/files/740901/fix_patch.txt)

No idea how to use that patch, something about [git apply](https://ariejan.net/2009/10/26/how-to-create-and-apply-a-patch-with-git/)

**Comment by FleventyFive** [comment]
Build system fixed, thanks for the help!
